#########
#
# workshop-template-b, evanwill
# a Jekyll template for a simple workshop website
# https://github.com/evanwill/workshop-template-b
#
#########

#######
# SITE SETTINGS
#
# title appears in the header
title: Text mining & analysis
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: tools
# description, keywords, and image for meta tags
# these do not visibility appear on the pages, but used for SEO
description: "Skills for mining and analysing text"
keywords: "text, data, digital humanities, workshop"
# featured-image is added to metadata tags for social media sharing
# use a relative path to image in this repository or full URL
featured-image: "/images/GC_Campus_LM-3181.jpg"
# add search box to footer? true/false
search: true

# author settings for cc-by, appears in the footer and credits
author: Griffith University Library
# your github username for link [optional]
github_username: GriffithUniLibrary
# year or date published
pub_year: 2022
# location of code, the full url to your github repository
repo: "https://github.com/GriffithUniLibrary/intro-text-mining-analysis/"

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url: https://GULibrarySandbox.github.io
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl: /intro-text-mining-analysis-2022


##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id: UA-139142134-4

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
